# Generated by Django 3.2.8 on 2021-10-31 09:02

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default title !!!', max_length=450)),
                ('image', models.ImageField(blank=True, default='CourseDefault.jpg', null=True, upload_to='Course/%Y/%m/%d/', verbose_name='Main Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/%d/', verbose_name='2nd Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/%d/', verbose_name='3rd Image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Course/%Y/%m/%d/', verbose_name='4th Image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Course Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount Price')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('additional_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Course')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-created'],
            },
        ),
    ]
