# Generated by Django 3.2.8 on 2021-11-01 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CourseManagement', '0002_historicalitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='HistoricalItem',
            new_name='HistoricalCourse',
        ),
        migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course'},
        ),
    ]
